name: Flutter_CI

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: ‘zulu’
        java-version: ‘11’
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.10'
        
    - name: List repository contents
      run: ls $GITHUB_WORKSPACE
      
    - name: Entering in the project root
      run: cd $GITHUB_WORKSPACE/guia_unb
    
    - name: Getting the dependencies for the Flutter project
      run: flutter pub get
 
    - name: Run tests for Flutter
      run: flutter test --coverage

    - name: Running lint
      run: flutter analyze
