name: Flutter_CI

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./guia_unb

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
          java-version: 11
          distribution: temurin
    
    - name: Clone Flutter repository with master channel
      uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
      with:
          channel: master
    
    - name: Getting the dependencies for the Flutter project
      run: flutter pub get
 
    - name: Run tests for Flutter
      run: flutter test --coverage

    - name: Running lint
      run: flutter analyze
      
    - name: Build apk
      run: flutter build apk
