name: Flutter_CI

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.3.10'
        
    - name: Entering in the project root
      run: cd guia_unb
    
    - name: Getting the dependencies for the Flutter project
      run: flutter pub get
      
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
 
    - name: Run tests for Flutter
      run: flutter test --coverage

    - name: Running lint
      run: flutter analyze
